name: JLab Templates

contact_numbers:
  - type: phone
    numbers:
      - "+27 23 456 7890"
      - "+27 23 456 7891"
  - type: mobile
    numbers:
      - "+27 34 567 8901"
      - "+27 34 567 8911"
  - type: fax
    numbers:
      - "+27 12 345 6789"
      - "+27 12 345 6780"

addresses:
  - type: Physical
    address1: "Parkwood building 2b"
    address2: "63 Grosvernor Rd"
    area: Bryanston
    city: Johannesburg
    postal_code: "0119"
    country: South Africa
    map_url: "https://goo.gl/WWDE4C"
  - type: Postal
    address1: "P.O. Box 3890"
    area: Theresapark
    city: Pretoria
    postal_code: "0182"
    country: South Africa

collections:
  services:
    output: true
  products:
    output: true
