name: JLab Templates


header:
  logo:
    enabled: true
    url: "http://yoursite.com"
    alt: "Your site Logo"
  slogan:
    enabled: true
    text: "Some slogan text"

contact_numbers:
  - type: phone
    numbers:
      - "+27 23 456 7890"
      - "+27 23 456 7891"
  - type: mobile
    numbers:
      - "+27 34 567 8901"
      - "+27 34 567 8911"
  - type: fax
    numbers:
      - "+27 12 345 6789"
      - "+27 12 345 6780"

social_accounts:
  - name: Facebook
    url: "http://facebook.com"
    icon: facebook
  - name: Twitter
    url: "http://twitter.com"
    icon: twitter
  - name: LinkedIn
    url: "http://linkedin.com"
    icon: linkedin

addresses:
  - type: Physical
    address1: "Parkwood building 2b"
    address2: "63 Grosvernor Rd"
    area: Bryanston
    city: Johannesburg
    postal_code: "0119"
    country: South Africa
    map_url: "https://goo.gl/WWDE4C"
  - type: Postal
    address1: "P.O. Box 3890"
    area: Theresapark
    city: Pretoria
    postal_code: "0182"
    country: South Africa

collections:
  services:
    output: true
  products:
    output: true
