name: JLab Templates

contact_numbers: 
  - type: phone
    numbers: 
      - "+27 23 456 7890"
      - "+27 23 456 7891"
  - type: mobile
    numbers:
      - "+27 34 567 8901"
      - "+27 34 567 8911"
  - type: fax
    numbers:
      - "+27 12 345 6789"
      - "+27 12 345 6780"
      
social_accounts:
  - name: Facebook
    url: "http://facebook.com"
    icon: facebook
  - name: Twitter
    url: "http://twitter.com"
    icon: twitter
  - name: LinkedIn
    url: "http://linkedin.com"
    icon: linkedin

